<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<section xmlns="http://docbook.org/ns/docbook" version="5.0" xmlns:xlink="http://www.w3.org/1999/xlink" xml:id="_classself_1_1exception" xml:lang="en-US">
<title>self::exception Class Reference</title>
<indexterm><primary>self::exception</primary></indexterm>
<para>Inheritance diagram for self::exception:    <informalfigure>
        <mediaobject>
            <imageobject>
                <imagedata width="50%" align="center" valign="middle" scalefit="0" fileref="classself_1_1exception.png"></imagedata>
            </imageobject>
        </mediaobject>
    </informalfigure>
</para>
<simplesect>
    <title>Public Member Functions    </title>
        <itemizedlist>
            <listitem><para><anchor xml:id="_classself_1_1exception_1ad17db6cbf4969804c88c557bcee1d2de"/><emphasis role="strong">exception</emphasis> (std::string ss)</para>
</listitem>
            <listitem><para><anchor xml:id="_classself_1_1exception_1a6ca3b55fc64cd6184522f1c0874511e4"/>const char * <emphasis role="strong">what</emphasis> () const  throw ()</para>
</listitem>
        </itemizedlist>
</simplesect>
<para>
The documentation for this class was generated from the following file:</para>
D:/My Hosted Projects/Data Structure and Algorithms/cpp14/Utility_/include/Utility/Utility.hpp</section>
